package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

/**
 * AlertEventLog generated by hbm2java
 */
public class AlertEventLog implements java.io.Serializable {

	private AlertEventLogId id;

	public AlertEventLog() {
	}

	public AlertEventLog(AlertEventLogId id) {
		this.id = id;
	}

	public AlertEventLogId getId() {
		return this.id;
	}

	public void setId(AlertEventLogId id) {
		this.id = id;
	}

}
