package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int id;
	private String firstName;
	private String lastName;
	private String emailId;
	private String loginId;
	private String passwd;
	private Character status;
	private String activationKey;
	private String primaryContact;
	private String secondaryContact;
	private Date updatedTime;
	private Date createdTime;
	private Integer failedLoginCount;
	private Set userDevices = new HashSet(0);
	private Set userAlertConfigurations = new HashSet(0);

	public Users() {
	}

	public Users(int id, String emailId, String loginId, String passwd) {
		this.id = id;
		this.emailId = emailId;
		this.loginId = loginId;
		this.passwd = passwd;
	}

	public Users(int id, String firstName, String lastName, String emailId, String loginId, String passwd,
			Character status, String activationKey, String primaryContact, String secondaryContact, Date updatedTime,
			Date createdTime, Integer failedLoginCount, Set userDevices, Set userAlertConfigurations) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailId = emailId;
		this.loginId = loginId;
		this.passwd = passwd;
		this.status = status;
		this.activationKey = activationKey;
		this.primaryContact = primaryContact;
		this.secondaryContact = secondaryContact;
		this.updatedTime = updatedTime;
		this.createdTime = createdTime;
		this.failedLoginCount = failedLoginCount;
		this.userDevices = userDevices;
		this.userAlertConfigurations = userAlertConfigurations;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public String getActivationKey() {
		return this.activationKey;
	}

	public void setActivationKey(String activationKey) {
		this.activationKey = activationKey;
	}

	public String getPrimaryContact() {
		return this.primaryContact;
	}

	public void setPrimaryContact(String primaryContact) {
		this.primaryContact = primaryContact;
	}

	public String getSecondaryContact() {
		return this.secondaryContact;
	}

	public void setSecondaryContact(String secondaryContact) {
		this.secondaryContact = secondaryContact;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Integer getFailedLoginCount() {
		return this.failedLoginCount;
	}

	public void setFailedLoginCount(Integer failedLoginCount) {
		this.failedLoginCount = failedLoginCount;
	}

	public Set getUserDevices() {
		return this.userDevices;
	}

	public void setUserDevices(Set userDevices) {
		this.userDevices = userDevices;
	}

	public Set getUserAlertConfigurations() {
		return this.userAlertConfigurations;
	}

	public void setUserAlertConfigurations(Set userAlertConfigurations) {
		this.userAlertConfigurations = userAlertConfigurations;
	}

}
