package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

/**
 * UserDevice generated by hbm2java
 */
public class UserDevice implements java.io.Serializable {

	private UserDeviceId id;
	private Device device;
	private Users users;

	public UserDevice() {
	}

	public UserDevice(UserDeviceId id, Device device, Users users) {
		this.id = id;
		this.device = device;
		this.users = users;
	}

	public UserDeviceId getId() {
		return this.id;
	}

	public void setId(UserDeviceId id) {
		this.id = id;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
