package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

/**
 * UserAlertConfiguration generated by hbm2java
 */
public class UserAlertConfiguration implements java.io.Serializable {

	private UserAlertConfigurationId id;
	private AlertType alertType;
	private Users users;

	public UserAlertConfiguration() {
	}

	public UserAlertConfiguration(UserAlertConfigurationId id, AlertType alertType, Users users) {
		this.id = id;
		this.alertType = alertType;
		this.users = users;
	}

	public UserAlertConfigurationId getId() {
		return this.id;
	}

	public void setId(UserAlertConfigurationId id) {
		this.id = id;
	}

	public AlertType getAlertType() {
		return this.alertType;
	}

	public void setAlertType(AlertType alertType) {
		this.alertType = alertType;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
