package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private int id;
	private String deviceId;
	private String imei;
	private Character deviceStatus;
	private Date createdTime;
	private String driverName;
	private String driverId;
	private String apiKey;
	private Set geoFencingDatas = new HashSet(0);
	private Set deviceLogEventses = new HashSet(0);
	private Set deviceExts = new HashSet(0);
	private Set userDevices = new HashSet(0);
	private Set voilationsLogs = new HashSet(0);

	public Device() {
	}

	public Device(int id, String deviceId) {
		this.id = id;
		this.deviceId = deviceId;
	}

	public Device(int id, String deviceId, String imei, Character deviceStatus, Date createdTime, String driverName,
			String driverId, String apiKey, Set geoFencingDatas, Set deviceLogEventses, Set deviceExts, Set userDevices,
			Set voilationsLogs) {
		this.id = id;
		this.deviceId = deviceId;
		this.imei = imei;
		this.deviceStatus = deviceStatus;
		this.createdTime = createdTime;
		this.driverName = driverName;
		this.driverId = driverId;
		this.apiKey = apiKey;
		this.geoFencingDatas = geoFencingDatas;
		this.deviceLogEventses = deviceLogEventses;
		this.deviceExts = deviceExts;
		this.userDevices = userDevices;
		this.voilationsLogs = voilationsLogs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public Character getDeviceStatus() {
		return this.deviceStatus;
	}

	public void setDeviceStatus(Character deviceStatus) {
		this.deviceStatus = deviceStatus;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	public String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	public String getApiKey() {
		return this.apiKey;
	}

	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	}

	public Set getGeoFencingDatas() {
		return this.geoFencingDatas;
	}

	public void setGeoFencingDatas(Set geoFencingDatas) {
		this.geoFencingDatas = geoFencingDatas;
	}

	public Set getDeviceLogEventses() {
		return this.deviceLogEventses;
	}

	public void setDeviceLogEventses(Set deviceLogEventses) {
		this.deviceLogEventses = deviceLogEventses;
	}

	public Set getDeviceExts() {
		return this.deviceExts;
	}

	public void setDeviceExts(Set deviceExts) {
		this.deviceExts = deviceExts;
	}

	public Set getUserDevices() {
		return this.userDevices;
	}

	public void setUserDevices(Set userDevices) {
		this.userDevices = userDevices;
	}

	public Set getVoilationsLogs() {
		return this.voilationsLogs;
	}

	public void setVoilationsLogs(Set voilationsLogs) {
		this.voilationsLogs = voilationsLogs;
	}

}
