package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

/**
 * DeviceExt generated by hbm2java
 */
public class DeviceExt implements java.io.Serializable {

	private int deviceId;
	private Device device;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String pincode;

	public DeviceExt() {
	}

	public DeviceExt(int deviceId, Device device) {
		this.deviceId = deviceId;
		this.device = device;
	}

	public DeviceExt(int deviceId, Device device, String addressLine1, String addressLine2, String city, String state,
			String pincode) {
		this.deviceId = deviceId;
		this.device = device;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
	}

	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

}
