package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

/**
 * GeoFencingData generated by hbm2java
 */
public class GeoFencingData implements java.io.Serializable {

	private int id;
	private Device device;
	private byte[] fencingData;

	public GeoFencingData() {
	}

	public GeoFencingData(int id, Device device) {
		this.id = id;
		this.device = device;
	}

	public GeoFencingData(int id, Device device, byte[] fencingData) {
		this.id = id;
		this.device = device;
		this.fencingData = fencingData;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public byte[] getFencingData() {
		return this.fencingData;
	}

	public void setFencingData(byte[] fencingData) {
		this.fencingData = fencingData;
	}

}
