package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * LocationTypes generated by hbm2java
 */
public class LocationTypes implements java.io.Serializable {

	private int id;
	private String type;
	private String description;
	private Set deviceLogEventses = new HashSet(0);

	public LocationTypes() {
	}

	public LocationTypes(int id, String type) {
		this.id = id;
		this.type = type;
	}

	public LocationTypes(int id, String type, String description, Set deviceLogEventses) {
		this.id = id;
		this.type = type;
		this.description = description;
		this.deviceLogEventses = deviceLogEventses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDeviceLogEventses() {
		return this.deviceLogEventses;
	}

	public void setDeviceLogEventses(Set deviceLogEventses) {
		this.deviceLogEventses = deviceLogEventses;
	}

}
