package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

/**
 * UserDeviceId generated by hbm2java
 */
public class UserDeviceId implements java.io.Serializable {

	private int userId;
	private int deviceId;

	public UserDeviceId() {
	}

	public UserDeviceId(int userId, int deviceId) {
		this.userId = userId;
		this.deviceId = deviceId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(int deviceId) {
		this.deviceId = deviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserDeviceId))
			return false;
		UserDeviceId castOther = (UserDeviceId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getDeviceId() == castOther.getDeviceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getDeviceId();
		return result;
	}

}
