package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

/**
 * UserAlertConfigurationId generated by hbm2java
 */
public class UserAlertConfigurationId implements java.io.Serializable {

	private int userId;
	private int alertDeviceType;
	private String deviceConfiguration;

	public UserAlertConfigurationId() {
	}

	public UserAlertConfigurationId(int userId, int alertDeviceType) {
		this.userId = userId;
		this.alertDeviceType = alertDeviceType;
	}

	public UserAlertConfigurationId(int userId, int alertDeviceType, String deviceConfiguration) {
		this.userId = userId;
		this.alertDeviceType = alertDeviceType;
		this.deviceConfiguration = deviceConfiguration;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getAlertDeviceType() {
		return this.alertDeviceType;
	}

	public void setAlertDeviceType(int alertDeviceType) {
		this.alertDeviceType = alertDeviceType;
	}

	public String getDeviceConfiguration() {
		return this.deviceConfiguration;
	}

	public void setDeviceConfiguration(String deviceConfiguration) {
		this.deviceConfiguration = deviceConfiguration;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserAlertConfigurationId))
			return false;
		UserAlertConfigurationId castOther = (UserAlertConfigurationId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getAlertDeviceType() == castOther.getAlertDeviceType())
				&& ((this.getDeviceConfiguration() == castOther.getDeviceConfiguration())
						|| (this.getDeviceConfiguration() != null && castOther.getDeviceConfiguration() != null
								&& this.getDeviceConfiguration().equals(castOther.getDeviceConfiguration())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getAlertDeviceType();
		result = 37 * result + (getDeviceConfiguration() == null ? 0 : this.getDeviceConfiguration().hashCode());
		return result;
	}

}
