package com.evercons.database.beans;
// Generated Nov 29, 2016 9:20:09 PM by Hibernate Tools 5.1.0.CR1

import java.util.Date;

/**
 * VoilationsLog generated by hbm2java
 */
public class VoilationsLog implements java.io.Serializable {

	private int id;
	private Device device;
	private Integer deviceId;
	private Date activityTime;
	private Character alertStatus;

	public VoilationsLog() {
	}

	public VoilationsLog(int id, Device device) {
		this.id = id;
		this.device = device;
	}

	public VoilationsLog(int id, Device device, Integer deviceId, Date activityTime, Character alertStatus) {
		this.id = id;
		this.device = device;
		this.deviceId = deviceId;
		this.activityTime = activityTime;
		this.alertStatus = alertStatus;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public Integer getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	public Date getActivityTime() {
		return this.activityTime;
	}

	public void setActivityTime(Date activityTime) {
		this.activityTime = activityTime;
	}

	public Character getAlertStatus() {
		return this.alertStatus;
	}

	public void setAlertStatus(Character alertStatus) {
		this.alertStatus = alertStatus;
	}

}
